const currencies = {
    AED: { nom: "Dirham des Émirats Arabes Unis", pays: "Emirats Arabes Unis" },
    AFN: { nom: "Afghan Afghan", pays: "Afghanistan" },
    ALL: { nom: "Lek albanais", pays: "Albanie" },
    AMD: { nom: "Dram arménien", pays: "Arménie" },
    ANG: { nom: "Florin des Antilles néerlandaises", pays: "Antilles néerlandaises" },
    AOA: { nom: "Kwanza angolais", pays: "Angola" },
    ARS: { nom: "Peso argentin", pays: "Argentine" },
    AUD: { nom: "Dollar australien", pays: "Australie" },
    AWG: { nom: "Florin d'Aruba", pays: "Aruba" },
    AZN: { nom: "Manat azerbaïdjanais", pays: "Azerbaïdjan" },
    BAM: { nom: "Marque de Bosnie-Herzégovine", pays: "Bosnie Herzégovine" },
    BBD: { nom: "Dollar de la Barbade", pays: "Barbade" },
    BDT: { nom: "Taka bangladais", pays: "Bangladesh" },
    BGN: { nom: "Lev bulgare", pays: "Bulgarie" },
    BHD: { nom: "Dinar bahreïnien", pays: "Bahreïn" },
    BIF: { nom: "Franc burundais", pays: "Burundi" },
    BMD: { nom: "Dollar bermudien", pays: "Bermudes" },
    BND: { nom: "Dollar brunéien", pays: "Brunéi" },
    BOB: { nom: "Boliviano bolivien", pays: "Bolivie" },
    BRL: { nom: "Réal brésilien", pays: "Brésil" },
    BSD: { nom: "Dollar bahaméen", pays: "Bahamas" },
    BTN: { nom: "Ngultrum bhoutanais", pays: "Bhoutan" },
    BWP: { nom: "Pula du Botswana", pays: "Botswana" },
    BYN: { nom: "Rouble biélorusse", pays: "Biélorussie" },
    BZD: { nom: "Dollar bélizien", pays: "Bélize" },
    CAD: { nom: "Dollar canadien", pays: "Canada" },
    CDF: { nom: "Franc congolais", pays: "République Démocratique du Congo" },
    CHF: { nom: "Franc suisse", pays: "Suisse" },
    CLP: { nom: "Peso chilien", pays: "Chili" },
    CNY: { nom: "Renminbi chinois", pays: "Chine" },
    COP: { nom: "Peso colombien", pays: "Colombie" },
    CRC: { nom: "Colon costaricain", pays: "Costa Rica" },
    CUP: { nom: "Peso Cubain", pays: "Cuba" },
    CVE: { nom: "Escudo Cap-Verdien", pays: "Cap-Vert" },
    CZK: { nom: "Couronne tchèque", pays: "République tchèque" },
    DJF: { nom: "Franc Djiboutien", pays: "Djibouti" },
    DKK: { nom: "Couronne danoise", pays: "Danemark" },
    DOP: { nom: "Peso Dominicain", pays: "République dominicaine" },
    DZD: { nom: "Dinar algérien", pays: "Algérie" },
    EGP: { nom: "Livre égyptienne", pays: "Egypte" },
    ERN: { nom: "Nakfa érythréen", pays: "Érythrée" },
    ETB: { nom: "Birr éthiopien", pays: "Ethiopie" },
    EUR: { nom: "euro", pays: "Union européenne" },
    FJD: { nom: "Dollar de Fidji", pays: "Fidji" },
    FKP: { nom: "Livre des Îles Falkland", pays: "les îles Falkland" },
    FOK: { nom: "Couronne féroïenne", pays: "Îles Féroé" },
    GBP: { nom: "Livre sterling", pays: "Royaume-Uni" },
    GEL: { nom: "Lari géorgien", pays: "Géorgie" },
    GGP: { nom: "Livre de Guernesey", pays: "Guernesey" },
    GHS: { nom: "Cédi ghanéen", pays: "Ghana" },
    GIP: { nom: "Livre de Gibraltar", pays: "Gibraltar" },
    GMD: { nom: "Dalasi gambien", pays: "La Gambie" },
    GNF: { nom: "Franc guinéen", pays: "Guinée" },
    GTQ: { nom: "Quetzal guatémaltèque", pays: "Guatemala" },
    GYD: { nom: "Dollar guyanais", pays: "Guyane" },
    HKD: { nom: "Dollar de Hong Kong", pays: "Hong Kong" },
    HNL: { nom: "Lempira hondurien", pays: "Honduras" },
    HRK: { nom: "Kuna croate", pays: "Croatie" },
    HTG: { nom: "Gourde haïtienne", pays: "Haïti" },
    HUF: { nom: "Forint hongrois", pays: "Hongrie" },
    IDR: { nom: "Rupiah indonésienne", pays: "Indonésie" },
    ILS: { nom: "Nouveau shekel israélien", pays: "Israël" },
    IMP: { nom: "Livre Manx", pays: "île de Man" },
    INR: { nom: "Roupie indienne", pays: "Inde" },
    IQD: { nom: "Dinar irakien", pays: "Irak" },
    IRR: { nom: "Rial iranien", pays: "L'Iran" },
    ISK: { nom: "Couronne islandaise", pays: "Islande" },
    JEP: { nom: "Livre de Jersey", pays: "Jersey" },
    JMD: { nom: "Dollar jamaïcain", pays: "Jamaïque" },
    JOD: { nom: "Dinar jordanien", pays: "Jordanie" },
    JPY: { nom: "Yen japonais", pays: "Japon" },
    KES: { nom: "Shilling kenyan", pays: "Kenya" },
    KGS: { nom: "Som kirghize", pays: "Kirghizistan" },
    KHR: { nom: "Riel cambodgien", pays: "Cambodge" },
    KID: { nom: "Dollar des Kiribati", pays: "Kiribati" },
    KMF: { nom: "Franc comorien", pays: "Comores" },
    KRW: { nom: "Won sud-coréen", pays: "Corée du Sud" },
    KWD: { nom: "Dinar koweïtien", pays: "Koweit" },
    KYD: { nom: "Dollar des îles Caïmans", pays: "Îles Caïmans" },
    KZT: { nom: "Tenge kazakh", pays: "Kazakhstan" },
    LAK: { nom: "Lao Kip", pays: "Laos" },
    LBP: { nom: "Livre libanaise", pays: "Liban" },
    LKR: { nom: "Roupie de Sri Lanka", pays: "Sri Lanka" },
    LRD: { nom: "Dollar libérien", pays: "Libéria" },
    LSL: { nom: "Loti du Lesotho", pays: "Lesotho" },
    LYD: { nom: "Dinar libyen", pays: "Libye" },
    MAD: { nom: "Dirham marocain", pays: "Maroc" },
    MDL: { nom: "Leu moldave", pays: "Moldavie" },
    MGA: { nom: "Ariary Malgache", pays: "Madagascar" },
    MKD: { nom: "Denar macédonien", pays: "Macédoine du Nord" },
    MMK: { nom: "Kyat birman", pays: "Birmanie" },
    MNT: { nom: "Tögrög mongol", pays: "Mongolie" },
    MOP: { nom: "Pataca macanaise", pays: "Macao" },
    MRU: { nom: "Ouguiya mauritanien", pays: "Mauritanie" },
    MUR: { nom: "Roupie mauricienne", pays: "Maurice" },
    MVR: { nom: "Rufiyaa maldivienne", pays: "Maldives" },
    MWK: { nom: "Kwacha du Malawi", pays: "Malawi" },
    MXN: { nom: "Peso mexicain", pays: "Mexique" },
    MYR: { nom: "Ringgit malaisien", pays: "Malaisie" },
    MZN: { nom: "Metical mozambicain", pays: "Mozambique" },
    NAD: { nom: "Dollar namibien", pays: "Namibie" },
    NGN: { nom: "Naira nigérian", pays: "Nigeria" },
    NIO: { nom: "Cordoue nicaraguayenne", pays: "Nicaragua" },
    NOK: { nom: "Couronne norvégienne", pays: "Norvège" },
    NPR: { nom: "Roupie népalaise", pays: "Népal" },
    NZD: { nom: "Dollar néo-zélandais", pays: "Nouvelle-Zélande" },
    OMR: { nom: "Rial d'Oman", pays: "Oman" },
    PAB: { nom: "Balboa panaméen", pays: "Panama" },
    PEN: { nom: "Sol péruvien", pays: "Pérou" },
    PGK: { nom: "Kina de Papouasie-Nouvelle-Guinée", pays: "Papouasie Nouvelle Guinée" },
    PHP: { nom: "Peso philippin", pays: "Philippines" },
    PKR: { nom: "Roupie pakistanaise", pays: "Pakistan" },
    PLN: { nom: "Zloty polonais", pays: "Pologne" },
    PYG: { nom: "Guaraní paraguayen", pays: "Paraguay" },
    QAR: { nom: "Riyal qatari", pays: "Qatar" },
    RON: { nom: "Leu roumain", pays: "Roumanie" },
    RSD: { nom: "Dinar serbe", pays: "Serbie" },
    RUB: { nom: "Rouble russe", pays: "Russie" },
    RWF: { nom: "Franc rwandais", pays: "Rwanda" },
    SAR: { nom: "Riyal saoudien", pays: "Arabie Saoudite" },
    SBD: { nom: "Dollar des Îles Salomon", pays: "Les îles Salomon" },
    SCR: { nom: "Roupie Seychelloise", pays: "les Seychelles" },
    SDG: { nom: "Livre soudanaise", pays: "Soudan" },
    SEK: { nom: "Couronne suédoise", pays: "Suède" },
    SGD: { nom: "Dollar de Singapour", pays: "Singapour" },
    SHP: { nom: "Livre de Sainte-Hélène", pays: "Sainte-Hélène" },
    SLL: { nom: "Sierra Léonais Leone", pays: "Sierra Leone" },
    SOS: { nom: "Shilling somalien", pays: "Somalie" },
    SRD: { nom: "Dollar surinamais", pays: "Surinam" },
    SSP: { nom: "Livre sud-soudanaise", pays: "Soudan du sud" },
    STN: { nom: "São Tomé et Príncipe Dobra", pays: "São Tomé et Príncipe" },
    SYP: { nom: "Livre syrienne", pays: "Syrie" },
    SZL: { nom: "Lilangeni Eswatini", pays: "Eswatini" },
    THB: { nom: "Baht thaïlandais", pays: "Thaïlande" },
    TJS: { nom: "Somoni tadjik", pays: "Tadjikistan" },
    TMT: { nom: "Manat du Turkménistan", pays: "Turkménistan" },
    TND: { nom: "Dinar tunisien", pays: "Tunisie" },
    TOP: { nom: "Pa'anga tongan", pays: "Tonga" },
    TRY: { nom: "Lire turque", pays: "Turquie" },
    TTD: { nom: "Dollar de Trinité-et-Tobago", pays: "Trinité-et-Tobago" },
    TVD: { nom: "Dollar des Tuvalu", pays: "Tuvalu" },
    TWD: { nom: "Nouveau dollar de Taïwan", pays: "Taïwan" },
    TZS: { nom: "Shilling tanzanien", pays: "Tanzanie" },
    UAH: { nom: "Hryvnia ukrainienne", pays: "Ukraine" },
    UGX: { nom: "Shilling ougandais", pays: "Ouganda" },
    USD: { nom: "Dollar américain", pays: "États-Unis" },
    UYU: { nom: "Peso Uruguayen", pays: "Uruguay" },
    UZS: { nom: "So'm ouzbek", pays: "Ouzbékistan" },
    VES: { nom: "Bolivar Soberano vénézuélien", pays: "Venezuela" },
    VND: { nom: "Đồng vietnamien", pays: "Viêt Nam" },
    VUV: { nom: "Vanuatu Vatu", pays: "Vanuatu" },
    WST: { nom: "Samoan Tālā", pays: "Samoa" },
    XAF: { nom: "Franc CFA d’Afrique centrale", pays: "CEMAC" },
    XCD: { nom: "Dollar des Caraïbes orientales", pays: "Organisation des États des Caraïbes orientales" },
    XDR: { nom: "Droits de tirage spéciaux", pays: "Fond monétaire international" },
    XOF: { nom: "Franc CFA ouest-africain", pays: "CFA" },
    XPF: { nom: "Franc CFP", pays: "Collectivités d'Outre-Mer" },
    YER: { nom: "Rial yéménite", pays: "Yémen" },
    ZAR: { nom: "Rand sud-africain", pays: "Afrique du Sud" },
    ZMW: { nom: "Kwacha zambien", pays: "Zambie" },
    ZWL: { nom: "Dollar zimbabwéen", pays: "Zimbabwe" }
};

console.log(currencies);
